### ISSUE TITLE
Display Allergies in Patient Demographics

### ISSUE THREAD

**Issue by yozair** [HII-C/patient_viewer#14]
The goal is to display a patient's allergies in the top left corner of the screen (next to the patient's photo).

**Comment by kaaniboy** [comment]
@kristytaing @rnshah9 

This issue involves utilizing the [AllergyIntolerance](https://www.hl7.org/fhir/allergyintolerance.html) resource associated with patients in the FHIR standard.

The goal is to display a patient's allergies in the top left corner of the screen (next to the patient's photo). There are two main steps needed to implement this:

1. Modify the `patient.pug` file to create a spot for displaying allergies.
2. Add an additional method to the `condition.service.ts` file (ie, `loadAllergies()`) that is responsible for retrieving a patient's allergies. This step is a bit more difficult, and involves performing an HTTP request that will retrieve the data. You can take a look at the other methods in the file as a starting point.

Because this is a larger task, I assigned it to both of you, and you can decide how to split it up among yourselves.

Let me know if you run into any issues or have any questions (especially since this is a tougher task, and I didn't describe the smaller subtasks).

**Comment by kristytaing** [comment]
Just changed the display to work like this:
- no allergies = "Allergies: none"
- 1 allergy = "Allergies: (the allergy)"
- multiple allergies = "Allergies: multiple"
